#!/bin/bash

set -e; set -u


PROBLEMS="../elementary-probability.tex"
TMP="/tmp"
PE="../../problem-extractor/pe.py"

for KEYS in *.txt; do
    TEX=${KEYS/.txt/.tex}
    PDF=${KEYS/.txt/.pdf}

    if [[ $KEYS -nt $PDF  ]]; then
        $PE $KEYS $PROBLEMS > $TMP/$TEX
#        pe $KEYS $PROBLEMS
        pdflatex    -output-directory   $TMP $TMP/$TEX
        pdflatex    -output-directory   $TMP $TMP/$TEX
        cp $TMP/${KEYS/.txt/.pdf} `pwd`
    fi
done








